name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

permissions:
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v4.4.0

      - name: Use Node.js
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version: 22.23.2
          registry-url: https://registry.npmjs.org/
          cache: pnpm

      - name: Update npm
        run: npm install -g npm@latest

      - run: pnpm i

      - name: Prepare
        run: pnpm run dev:prepare

      - name: PNPM build
        run: pnpm run prepack

      - name: Publish to NPM
        run: pnpm publish --access public --no-git-checks
